### ISSUE TITLE
Possible job limit synchronization issue with Jupyter

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/puppet-magic_castle#104]
For one cluster I've recently created, they wanted a maximum job time of 15 minutes, so I changed the central Slurm config. However, the Jupyter interface still seems to default to 1 hour, which then means jobs initiated by Jupyter are not scheduled unless the user remembers to change the run time.

Does something need to be run after making such changes so Jupyter will pick them up?

**Comment by cmd-ntrf** [comment]
The JupyterHub spawner form does not consider Slurm configuration when defining the runtime limits (maybe it should... an issue could be filled there: [slurmformspawner](https://github.com/cmd-ntrf/slurmformspawner)).

The configuration of the runtime widget is static, but it can be modified by adding this:
```
jupyterhub::jupyterhub_config_hash:
  SbatchForm:
    runtime:
      min: 1.0
      def: 2.0
      max: 5.0
```
to : 
``` 
/etc/puppetlabs/data/user_data.yaml
``` 
on mgmt1.

This file content can also be controlled using the `hieradata` variable in the cluster block of the Terraform `main.tf` file.
Ref: https://github.com/ComputeCanada/magic_castle/tree/master/docs#414-hieradata-optional

JupyterHub Slurm Form Spawner Puppet module variables are documented here:
https://github.com/ComputeCanada/puppet-jupyterhub#slurmformspawners-options
