### ISSUE TITLE
Use config-less Slurm

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/puppet-magic_castle#105]
Now that more recent Slurm versions are possible, it would be handy if "config-less" support would be added:

https://slurm.schedmd.com/configless_slurm.html

**Comment by cmd-ntrf** [comment]
Can you provide more details on what configless would offer when compared to the current setup?

Based on Slurm docs:
> The slurmd on startup will reach out to a slurmctld that you specify and the config files will be pulled to the node.

My reading is this is useful when you do not already have a configuration management tool like Puppet, but I could be missing something.

**Comment by verdurin** [comment]
The main benefit is that you don't need to distribute the modified config file across all the nodes.

Certainly if you're handling Slurm config via Puppet or similar, it doesn't gain you much.

I've found with these ephemeral clusters that quite a lot of Slurm tuning may be required, and it makes that easier.

Would understand if you considered this a prop for the lazy...
