### ISSUE TITLE
Clean up of /tmp and /dev/shm on workers

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/puppet-magic_castle#112]
I noticed that SLURM doesn't clean up `/tmp` and `/dev/shm` after a job completes. It's probably not well suited to an epilog since the nodes are shared, but for long lived clusters it is probably wise to clean these periodically (e.g., remove all files belonging to users not active on the node in those dirs).

**Comment by cmd-ntrf** [comment]
Can you provide more details on what kind of jobs leave files in these directories? Slurm version? CentOS 7 or 8?

We already have an epilog that should clean these directories : 
https://github.com/ComputeCanada/puppet-magic_castle/blob/master/site/profile/files/slurm/epilog

The usage of the tmpfs spank plugin normally means thr users only sees the directories named after its job, and these are the directories that the epilog removes.
https://github.com/ComputeCanada/spank-cc-tmpfs_mounts

**Comment by ocaisa** [comment]
For example
```
sbatch --wrap="hostname && sleep 20 && env && lscpu" -o /tmp/test_alan.log
sbatch --wrap="hostname && sleep 20 && env && lscpu" -o /dev/shm/test_alan.log
```
but it looks like I just hit a cornercase, if I actually try to touch files within a job itself, these are indeed cleaned up.
