### ISSUE TITLE
Mokey users who try to use uppercase characters for Username get a wrong `$HOME`

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/puppet-magic_castle#118]
We're running a workshop today and a few users inputted usernames like `OCais`, these get converted to lowercase **but** the value for "Home directory" retains the uppercase. These directories don't exist so login ends up in `/`. Even if I fix the "Home directory" in IPA, the  value of `$HOME` is still incorrect after login, which means login succeeds but `cd` fails.

**Comment by cmd-ntrf** [comment]
I am sorry this happened during a workshop.

I will look into it. I am not sure wether the problem is Magic Castle, Mokey or 389DS. The home folder is created by parsing the directory server logs. This means the lowercasing of the username is probably done by 389DS.

**Comment by ocaisa** [comment]
It's fine, just took a while to figure out. It also triggered fail2ban for one user since they thought their username was `MyUser` (since that was what they inputted) but actually it was `myuser`. I guess some kind of sanitation should be done by mokey in the signup form (which is perhaps not a Magic Castle issue).

**Comment by ocaisa** [comment]
Correction, it looks like the value of `$HOME` is corrected but this takes some time (I guess puppet does this?).

**Comment by verdurin** [comment]
We saw something similar. Must admit I wasn't prepared for people trying to create mixed-case usernames...

**Comment by ocaisa** [comment]
Could be resolved by adding a lowercase check at https://github.com/ubccr/mokey/blob/master/server/signup.go/#L139 but since users can come from other places, this is perhaps not a complete fix.

**Comment by cmd-ntrf** [comment]
> Correction, it looks like the value of `$HOME` is corrected but this takes some time (I guess puppet does this?).

The value for $HOME was most likely cached in the login SSSD database which is invalidated at regular interval, hence the latency. The cache can be cleared with the following command:
```sss_cache -E``` 
It can also be used to clear the cache for a specific user:
```sss_cache -u username```

**Comment by cmd-ntrf** [comment]
I have create a PR for Mokey to fix this:
https://github.com/ubccr/mokey/pull/78

**Comment by cmd-ntrf** [comment]
My PR has been merge, a new version of Mokey (v0.5.5) has been released and I have rebuilt the Mokey RPM on copr.
https://copr.fedorainfracloud.org/coprs/cmdntrf/mokey/builds/

Upgrading Mokey with yum on existing clusters will fix this issue and new clusters will get the Mokey version with the fix.
