### ISSUE TITLE
Behaviour when `nb_users` is set to 0

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/puppet-magic_castle#119]
When the cluster is configured with no users (relying purely on mokey), there is no `def-sponsor00` group created which seems to have knock-on effects (no structure in for `/project` and `/scratch` for example).

**Comment by cmd-ntrf** [comment]
When relying purely on mokey, I expected the admin would create a group and assign users to it. The only requirement for that group is that its name should start one of the four prefixes harcoded here (I am planning to make the prefixes configurable eventually):
https://github.com/ComputeCanada/puppet-magic_castle/blob/2458ec8e931e24a1d96e07a48a12910ef072d441/site/profile/files/accounts/mkproject.sh#L22

Assigning such group to the users created through Mokey will trigger the creation of the associated project folders and Slurm accounts. The admin could manually create `def-sponsor00`, or choose a more relevant name for its workshop.

This is documented here:
https://github.com/ComputeCanada/magic_castle/blob/e3c0bdb38d7142f4331d5dfdb97a6a46d11116bc/docs/README.md#1032-with-mokey . If you have ideas on how to improve this feature documentation or discoverability, I am all ears.

home and scratch folders rely only on user account creation. If one of these folder hierarchy is missing, there is a bug somewhere, but unrelated to `def-sponsor00`.

**Comment by ocaisa** [comment]
To be honest the docs are pretty clear, I just didn't go looking when I came across the issue.

I guess one thing that made me think this was a potential bug was that you end up with output that says
```
guest_usernames = "user[1-0]"
```

Is it possible to have Terraform print a message if I choose `nb_users = 0` to warn people to go read the docs? Something like
```
You have chosen to create user accounts yourself (`nb_users = 0`), please read the documentation on how to manage this at https://github.com/ComputeCanada/magic_castle/blob/main/docs/README.md#103-add-a-user-account 
```

**Comment by ocaisa** [comment]
Addressed in https://github.com/ComputeCanada/magic_castle/pull/153

**Comment by ocaisa** [comment]
https://github.com/ComputeCanada/magic_castle/pull/153 is merged so closing this
