### ISSUE TITLE
[feature] Support multiple URL in workshop material URL

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/puppet-magic_castle#126]
`profile::workshop::userzip_url` is a String. 
A list of string would allow multiple zip file to be extracted. e.g.
```
profile::workshop::userzip_url: ['url/zip1', 'url/zip2']
```

**Comment by cmd-ntrf** [comment]
Proposed solution:
https://github.com/ComputeCanada/puppet-magic_castle/pull/191
