### ISSUE TITLE
Handling heterogenous cpu architectures

### ISSUE THREAD

**Issue by mboisson** [ComputeCanada/puppet-magic_castle#14]
On our OpenStack cloud, there are Skylake, Broadwell and Ivy Bridge nodes (avx512, avx2, avx).

This results in the following possible scenario : login node is avx512 or avx2 capable, and compute nodes are only avx capable. You then compile something using the login node, and running on the compute nodes results in illegal instructions. 

Ideally, the cluster configuration would figure out what is the lowest common denominator and pin RSNT_ARCH to this architecture. 

Pinning can be done using
```
[root@login01 ~]# cat /etc/profile.d/z-000-arch.sh
export RSNT_ARCH=avx
```

**Comment by cmd-ntrf** [comment]
A first pass at the solution has been pushed on branch `consul_arch` and it is currently being tested.

**Comment by cmd-ntrf** [comment]
`consul_arch` branch has been merged.
