### ISSUE TITLE
Removing `dhclient` fails on Rocky Linux 8.5

### ISSUE THREAD

**Issue by SebastianAchilles** [ComputeCanada/puppet-magic_castle#166]
When building magic castle with Rocky Linux 8.5 (`Rocky-8-GenericCloud-8.5-20211114.2.x86_64`) removing of `dhclient` (https://github.com/ComputeCanada/puppet-magic_castle/blob/main/site/profile/manifests/freeipa.pp#L28-L32) fails:

```
Jan 03 09:08:50 mgmt1 puppet-agent[1077]: Execution of '/usr/bin/rpm -e dhcp-client' returned 1: error: Failed dependencies:
Jan 03 09:08:50 mgmt1 puppet-agent[1077]:         dhcp-client is needed by (installed) cloud-init-21.1-7.el8_5.3.noarch
Jan 03 09:08:50 mgmt1 puppet-agent[1077]: (/Stage[main]/Profile::Freeipa::Base/Package[dhclient]/ensure) change from '12:4.3.6-45.el8' to 'absent' failed: Execution of '/usr/bin/rpm -e dhcp-client' returned 1: error: Failed dependencies:
Jan 03 09:08:50 mgmt1 puppet-agent[1077]: (/Stage[main]/Profile::Freeipa::Base/Package[dhclient]/ensure)         dhcp-client is needed by (installed) cloud-init-21.1-7.el8_5.3.noarch
```

Removing `dhclient` worked with Rocky Linux 8.4 where an older version of `cloud-init` was used:
```
cloud-init.noarch                   20.3-10.el8_4.5                           @appstream
```

**Comment by ocaisa** [comment]
I saw this too yesterday on CentOS 8

**Comment by cmd-ntrf** [comment]
Removing dhclient was meant to prevent issue with `resolv.conf` being overwritten when the DHCP lease is renewed. I am not sure why cloud-init requires dhclient, but now that the configuration is `resolv.conf` is done by NetworkManager, we should be able to leave dhclient installed even if it has no use.
