### ISSUE TITLE
[cvmfs] Load gcc module by default

### ISSUE THREAD

**Issue by bartoldeman** [ComputeCanada/puppet-magic_castle#18]
Current Magic Castle instances load the CC stack StdEnv module which loads the Intel compiler module by default, and that gives a message about non-commercial the first time you log in. Since by default the instances can't access the Intel compiler license server it would be better to define a StdEnv alternative that uses GCC and use that instead.

(this requires some work on the CC CVMFS config side which I can do).

**Comment by cmd-ntrf** [comment]
What would be the best way to achieve this?

**Comment by cmd-ntrf** [comment]
@bartoldeman care to comment on what would be the best way to load GCC by default in Magic Castle?

**Comment by mboisson** [comment]
Defining an environment variable, i.e. 
```
export LMOD_SYSTEM_DEFAULT_MODULES="StdEnv/2016.4 gcc/5.4.0"
``` 

or
```
export LMOD_SYSTEM_DEFAULT_MODULES="StdEnv/2018.3 gcc/7.3.0"
```

**Comment by cmd-ntrf** [comment]
@mboisson do you know what Bart meant by 
> this requires some work on the CC CVMFS config side which I can do
?

**Comment by mboisson** [comment]
Ah, I think he meant defining a new `StdEnv-gcc` module, but I am not sure this is needed. @bartoldeman, don't you think the solution above is good enough ?

**Comment by bartoldeman** [comment]
I was thinking of a more generic solution as in "if no restricted repo is available then load gcc as default"

**Comment by mboisson** [comment]
Ahhh... 🤔   but this would be a change of behavior, which may surprise some, and may potentially swap the software stack if the restricted repository becomes unmountable for some period of time

**Comment by bartoldeman** [comment]
Sure it may be surprising but the current default is broken (ie. mpicc doesn't work).

we already set the CC_RESTRICTED environment variable and hide modules for this purpose.

"if the restricted repository becomes unmountable for some period of time" -- that would already be a big issue on the clusters, much bigger than the software stack being swapped.

**Comment by mboisson** [comment]
so, we could simply define 
`LMOD_SYSTEM_DEFAULT="StdEnv gcc"`  when `CC_RESTRICTED` is set to false I think.

**Comment by verdurin** [comment]
While I have been setting that variable manually, it would be good to change the default and/or find a way of avoiding that warning about licensing that currently appears.

**Comment by cmd-ntrf** [comment]
The default will be customizable by configuring the variable `profile::cvmfs::lmod_default_module` in the hieradata. It will be a list of module names, and by default it will contain `['nixpkgs/16.09', 'imkl/2018.3.222', 'gcc/7.3.0', 'openmpi/3.1.2']`.
