### ISSUE TITLE
squid maximum_object_size lower than allowable cvmfs chunk sizes

### ISSUE THREAD

**Issue by jflandry** [ComputeCanada/puppet-magic_castle#20]
site/profile/templates/squid/squid.conf.epp Line 28:
`maximum_object_size            4096 KB`

This limit is lower than the (default) allowable cvmfs chunk size, which is not optimal.

From Ryan P. Taylor:
```
$ grep "DEFAULT.*CHUNK_SIZE="  /usr/bin/cvmfs_server 
CVMFS_DEFAULT_MIN_CHUNK_SIZE=4194304
CVMFS_DEFAULT_AVG_CHUNK_SIZE=8388608
CVMFS_DEFAULT_MAX_CHUNK_SIZE=16777216
```

Reference data repositories such as bioinformatics tend to use larger chunks (32-128 megabytes), a more reasonable squid maximum_object_size might be `131072 KB` instead.

**Comment by jflandry** [comment]
Ryan P. Taylor confirms that CC data repos use CVMFS_MAX_CHUNK_SIZE=67108864

**Comment by cmd-ntrf** [comment]
Thanks! 

I bumped the limit in commit fd440454401e98f91e0ec8a35372764ba3c64a0b.
