### ISSUE TITLE
PTR dns record do not update correctly when subnet != /24

### ISSUE THREAD

**Issue by guilbaults** [ComputeCanada/puppet-magic_castle#22]
Puppet will try to execute the following command:
`kinit_wrapper ipa dnsrecord-del 0.0.0.10.in-addr.arpa.  --del-all`

The entire command is:
`kinit_wrapper ipa dnsrecord-del ${reverse_zone} ${ptr_record} --del-all`

The variable`${ptr_record}` is left blank so the command fail and puppet cannot fix the PTR record.

**Comment by cmd-ntrf** [comment]
The function that creates the PTR record is defined here:
https://github.com/ComputeCanada/puppet-magic_castle/blob/master/site/profile/functions/getptrrecord.pp

Normally, there is nothing specific to /24. Could you provide some example hieradata so we could find where the function breaks?
