### ISSUE TITLE
Sign-ups not automatically a member of the `ipa-user` group

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/puppet-magic_castle#234]
When running MC 12.3.0 I found that sign-up users are not added to the `ipa-user` group. There is another group `ipausers` which says is the default group for all users, so I think there is just a naming issue here.

![Screenshot (67)](https://user-images.githubusercontent.com/3840437/234837754-0fc053a5-5fdf-41dd-bfaf-5b6e6c21f3d7.png)

**Comment by cmd-ntrf** [comment]
Ah shoot I forgot about Mokey when designing the HBAC rules.

The `ipa-` group name is named after LDAP users defined with puppet.

I will need to implement an hbac rule for Mokey created user.

**Comment by ocaisa** [comment]
Fixed
