### ISSUE TITLE
Fail2Ban configuration error

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/puppet-magic_castle#25]
```
2020-02-16 13:38:31,142 fail2ban.transmitter   
 [3237]: ERROR   Jail 'sshd' skipped, because of wrong configuration: Unable to read the filter 'sshd-aggressive'
```

**Comment by verdurin** [comment]
Seems like the fix is something like to set `mode = aggressive` or `mode = ddos` though other changes may also be required.

**Comment by cmd-ntrf** [comment]
Our puppet module for fail2ban was designed with `failban-0.9.7-1`. EPEL updated [fail2ban to `fail2ban-0.10.4-1.el7`](https://lists.fedoraproject.org/archives/list/epel-package-announce@lists.fedoraproject.org/message/K5YTDC6NCPASEZURMRQOPEEOSJMXZZ7R/) on 2019-12-09 then to [`fail2ban-0.10.5-2.el7`](https://lists.fedoraproject.org/archives/list/epel-package-announce@lists.fedoraproject.org/message/K5YTDC6NCPASEZURMRQOPEEOSJMXZZ7R/) on 2020-02-05.

We will need to review the whole module to make sure it is compatible with 0.10.5-2.
