### ISSUE TITLE
[idea] contrib folder for scripts in /opt

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/puppet-magic_castle#28]
Extra provisioning steps are sometime require when creating a cluster for workshops. For example, we sometime need to copy data in /project or create notebooks in users' home folder.

This steps are can be scripted. We could have a contrib repo that is copied by puppet where a cluster admin could find the scripts to complete the provisioning steps for a workshop.

**Comment by plstonge** [comment]
`pusersh`:

```
#!/usr/bin/env bash

for TMP_USER in $(ls /home | grep user);
do
  echo $TMP_USER:
  sudo su - $TMP_USER -c "$@"
done
```

**Comment by plstonge** [comment]
This one depends on the workshop: `update_home.sh`

```
#!/usr/bin/env bash

PYMAT="python-novice-inflammation"

cd $HOME

if [ -e "$PYMAT" ];
then
  cd $PYMAT && echo -n "- $PYMAT: " && git pull && git branch
else
  git clone -b cq-notebooks https://github.com/calculquebec/$PYMAT.git
fi
```

**Comment by plstonge** [comment]
Having our public SSH keys inside of each `userXY` account would also be great.
