### ISSUE TITLE
Use upstream Singularity?

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/puppet-magic_castle#29]
The version of `Singularity` provisioned from the `Copr` repo is quite old (`3.4.2`).

Is there any reason not to use the `EPEL` version which is kept up to date by Dave Dykstra?

**Comment by cmd-ntrf** [comment]
The EPEL version installs singularity in `/usr/bin/`, while Compute Canada module presumes all softwares will either be installed on CVMFS or in `/opt`.

The COPR version is not doing anything special except changing the installation prefix to match Compute Canada expectations.

The good news is that it is easy to generate a RPM for a newer version of singularity. I just built 3.5.3. I should probably look into hooking the RPM build on Copr to singularity releases on GitHub.
