### ISSUE TITLE
prometheus storage_retention can exceed mgmt1 storage capacity

### ISSUE THREAD

**Issue by cmd-ntrf** [ComputeCanada/puppet-magic_castle#30]
By default, mgm1 has only 10GB of storage in `/`. The current storage retention for Prometheus is undefined. This can exceed the amount of storage available for mgmt1 if the cluster is up for a long time.

In puppet-prometheus v8.x, the storage retention can be configured in hieradata with 
```
prometheus::server::storage_retention: '96h'
storage_retention_size: '10GB'
```

We should update puppet-prometheus to v8 and add the configuration variables to the hieradata.

Thanks to @bartoldeman for reporting this issue and @jflandry for helping with puppet-prometheus configuration.

**Comment by jflandry** [comment]
The second is actually:
`prometheus::storage_retention_size: '10GB'`

Note that the latest prometheus documentation marks the underlying option as experimental, and does not account for the WAL:
https://prometheus.io/docs/prometheus/latest/storage/
(look for `--storage.tsdb.retention.size`)
