### ISSUE TITLE
don't use CVMFS_STRICT_MOUNT anymore

### ISSUE THREAD

**Issue by rptaylor** [ComputeCanada/puppet-magic_castle#334]
https://github.com/ComputeCanada/puppet-magic_castle/blob/main/site/profile/templates/cvmfs/default.local.epp#L2

@cmd-ntrf   In the past we recommended to use CVMFS_STRICT_MOUNT=yes in one specific situation, when the CC config repo is used on a system that doesn't have access to the restricted repo.
That was before we added the CC repo config to the global default config repo. The original purpose of this setting is not really applicable anymore and I don't think there is a benefit to using it, whereas the disadvantage is it limits the accessibility and flexibility by arbitrarily blocking repos that users may otherwise be able to access and take advantage of.

MC deployments should use either of 2 deployment scenarios (this is true independently of this issue, but also a requirement to remove CVMFS_STRICT_MOUNT=yes) :
1. [Internal](https://wiki.alliancecan.ca/wiki/CVMFS_client_setup): The system has access to the restricted repo, and the CC config repo (the cvmfs-config-computecanada RPM) is used.
2. [Public](https://docs.alliancecan.ca/wiki/Accessing_CVMFS): The system does not have access to the restricted repo, and the CC config repo is not used. In this case all the standard default repos will be available, including soft.computecanada.ca and containers.computecanada.ca. Some other data repos will not be available this way yet, but will be after some changes later this year.

**Comment by cmd-ntrf** [comment]
Fix in #335 

@rptaylor can you validate?

**Comment by rptaylor** [comment]
I can't say whether the Puppet stuff is correct but if it is set up based on the wiki docs linked above it should be correct.

**Comment by mboisson** [comment]
I can test this

**Comment by mboisson** [comment]
Seems to work: 
```
[centos@cvmfs-client1 ~]$ cat /etc/cvmfs/default.local
CVMFS_REPOSITORIES="cvmfs-config.computecanada.ca,containers.computecanada.ca,data.rsnt.computecanada.ca,public.data.computecanada.ca,restricted.computecanada.ca,soft.computecanada.ca,soft-dev.computecanada.ca"
CVMFS_STRICT_MOUNT="no"
CVMFS_QUOTA_LIMIT=4096
CVMFS_HTTP_PROXY='http://192.168.185.110:3128;DIRECT'
```
