### ISSUE TITLE
Default  ephemeral mount point location

### ISSUE THREAD

**Issue by poquirion** [ComputeCanada/puppet-magic_castle#341]
Right now here is how MC deals with an effemeral disk, here /dev/vdb from cloud init logs:

```
cloud-init.log:2024-03-21 15:15:42,025 - openstack.py[DEBUG]: Mapped ephemeral0 to device /dev/vdb
cloud-init.log:2024-03-21 15:15:42,025 - cc_mounts.py[DEBUG]: Mapped metadata name ephemeral0 to /dev/vdb
cloud-init.log:2024-03-21 15:15:42,025 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => /dev/vdb
cloud-init.log:2024-03-21 15:15:42,068 - cc_mounts.py[DEBUG]: Changes to fstab: ['+ /dev/vdb /mnt auto defaults,nofail,x-systemd.requires=cloud-init.service,_netdev,comment=cloudconfig 0 2']
```

What would be the best way of mounting that in a user defined location, for example `/localscratch`?

**Comment by cmd-ntrf** [comment]
Actually, that's not how MC is dealing with ephemeral disk. This config is injected by OpenStack, and to be honest it is not very convenient, but I have yet found a way to overrule what the OpenStack admin have decided.

**Comment by poquirion** [comment]
aarrgh, It causes all sorts of problem because the cephfs are also mounted in `/mnt/<mnt-path>` along beinf mounted in `/<mnt-pth>`  is there a practical reason for having the cephfs mounted in two places?

**Comment by cmd-ntrf** [comment]
I was wrong. This is actually a default option for cloud-init to mount ephemeral0 directly on /mnt.

We could avoid this by telling cloud-init to mount it elsewhere.

**Comment by poquirion** [comment]
And if I am not mistaken, the only place where we play with cloud init right now it here... So adding that config might not be a one line in a file...
`/home/poq/sd4h/MC_repos/magic_castle/common/instance_config/puppet.yaml`

**Comment by poquirion** [comment]
unless it is acceptable to add the 
```
mounts:
  - [ ephemeral0, /localscratch, auto, "rw,seclabel,noatime,xattr,noacl", "0","0" ]
```
there

**Comment by poquirion** [comment]
https://cloudinit.readthedocs.io/en/latest/reference/examples.html#adjust-mount-points-mounted

**Comment by cmd-ntrf** [comment]
We won't have ephemeral0 mounted on /localscratch. It will instead be mounted in a subdirectory of /mnt and from there we will be able to mount bind to some place else with Puppet.

**Comment by poquirion** [comment]
It also seems that the destination needs to be explicitely created. So `mkdir /mnt/<dest>` need to run somewhere.

**Comment by cmd-ntrf** [comment]
cloud-init takes care of creating the subdirectory under /mnt.
