### ISSUE TITLE
Config to Enable/Disable fail2ban

### ISSUE THREAD

**Issue by ccoulombe** [ComputeCanada/puppet-magic_castle#35]
For some teaching workshop, it would be useful to disable fail2ban beforehand.

**Comment by cmd-ntrf** [comment]
That should be fairly easy to implement. As we speak, configuration of fail2ban is entirely hardcoded in the puppet module. We could add a few variable that would allow the control of fail2ban through hieradata.

fail2ban class : https://github.com/ComputeCanada/puppet-magic_castle/blob/master/site/profile/manifests/fail2ban.pp
fail2ban config file template : https://github.com/ComputeCanada/puppet-magic_castle/blob/master/site/profile/templates/fail2ban/jail.local.epp

I would propose we allow the control of jail enabling (lines 6 and 10) through hieradata variables, and also add a variable to include more ip to ignore (line 3).

The hieradata could be configured either at cluster creation or after.
