### ISSUE TITLE
update (or remove?) squid ACLs

### ISSUE THREAD

**Issue by rptaylor** [ComputeCanada/puppet-magic_castle#58]
https://github.com/ComputeCanada/puppet-magic_castle/blob/master/site/profile/templates/squid/squid.conf.epp
should be updated.

I am not sure if restricting the squid destination is completely necessary or suitable for MC , but if you want to, please see:
https://wiki.computecanada.ca/staff/CVMFS_client_setup#Proxy_configuration

This will be needed for https://github.com/ComputeCanada/magic_castle/issues/105

**Comment by rptaylor** [comment]
BTW I also see you have some custom refresh_pattern settings there. 
I would be careful about that , especially patterns that apply to .cvfms* files.
As far as I'm aware, frontier-squid is the best reference for CVMFS-specific squid cache settings, and it does not have any custom refresh_pattern settings. 
I believe this is all handled on the stratum server side, see the part about HTTP response headers from a stratum server here:
https://wiki.computecanada.ca/staff/CVMFS_Administration#Miscellaneous_tips_and_tricks

**Comment by cmd-ntrf** [comment]
If we have the list of CVMFS repositories in a variable, configured by the MC user in the hieradata, could we simply use the repositories url in the squid ACL instead of using the regexes suggested on the staff wiki?

**Comment by rptaylor** [comment]
No, a priori there is no straightforward surefire way to translate from repository names to the host names of the stratum servers which host them. You could define a mapping, but that is basically what the wiki page is for.

What is the reason to have a destination squid ACL for MC? IMO it is suitable if you have strict security policies and want to prevent people from downloading inappropriate content from the internet, and the squid is used to mediate and control *all* internet access, not just for CVMFS.  But use of CVMFS_STRICT_MOUNT already ensures that only "approved" repositories can be used anyway.

**Comment by cmd-ntrf** [comment]
Fixed by PR #62.
