### ISSUE TITLE
Support other cvmfs repos already configures in  /cvmfs/cvmfs-config.computecanada.ca/etc/cvmfs/config.d/

### ISSUE THREAD

**Issue by poquirion** [ComputeCanada/puppet-magic_castle#59]
I am especially interested in  ref.galaxy  ref.mugqic soft.galaxy and  soft.mugqic.

**Comment by rptaylor** [comment]
relies on #58

**Comment by cmd-ntrf** [comment]
Do we need squid refresh_patterns for other repos too?

**Comment by rptaylor** [comment]
I don't think any special refresh_patterns are needed (as discussed in #58 ) , but the current squid ACL blocks access to the stratum servers for mugqic and other repos.

**Comment by cmd-ntrf** [comment]
Fixed by PR #62.
