### ISSUE TITLE
Add Cloudflare load balancer cvmfs_acl_regex

### ISSUE THREAD

**Issue by jflandry** [ComputeCanada/puppet-magic_castle#64]
A new Cloudflare load balancer cvmfs s1 endpoint is now online (cvmfs-s1.computecanada.net)

`profile::squid::server::cvmfs_acl_regex:` in data/common.yaml need an additional entry:

`'^(cvmfs-.*\.computecanada\.net)$'`

Ref: https://wiki.computecanada.ca/staff/CVMFS_client_setup#Proxy_configuration

**Comment by cmd-ntrf** [comment]
Fixed in bce0f18bdf83cd6ecccf75f529b62ad0f5b93c2c.
Thanks!
