### ISSUE TITLE
Using the EESSI stack with Magic Castle

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/puppet-magic_castle#76]
I was playing around with Magic Castle today and I was wondering how much I would have to play with it to switch out the CC stack for the [EESSI](https://eessi.github.io/docs/) stack. I've never used puppet before so bear with me if I say something silly.

From what I can tell, I would need to update:
* https://github.com/ComputeCanada/puppet-magic_castle/blob/master/data/common.yaml
* https://github.com/ComputeCanada/puppet-magic_castle/blob/master/site/profile/manifests/cvmfs.pp
* https://github.com/ComputeCanada/puppet-magic_castle/blob/master/site/profile/manifests/jupyterhub.pp

Does that sounds about right? 

If I was to do this, is there a way to make this into a PR rather than forking the repo?

**Comment by cmd-ntrf** [comment]
It's a very cool idea.

You should not have to update `jupyterhub.pp`, just edit `common.yaml` and generalize `cvmfs.pp`. Nothing silly was said.

And yes, it could be integrated in the main code base with a PR. I can help with the PR if you have never used puppet.
