### ISSUE TITLE
Logrotate config should be added for Slurm

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/puppet-magic_castle#82]
Cf. https://wiki.fysik.dtu.dk/niflheim/Slurm_installation#id26 for a good example config

**Comment by cmd-ntrf** [comment]
Yes, and we should probably logrotate other log files too on login, mgmt and node.

There is a puppet module to configure logrotate easily:
https://forge.puppet.com/modules/puppet/logrotate#examples
