### ISSUE TITLE
GPU support failing

### ISSUE THREAD

**Issue by ocaisa** [ComputeCanada/puppet-magic_castle#91]
When trying to use GPU support I get a failure:
```
Feb  4 11:43:46 gpu-node2 puppet-agent[1074]: (/Stage[main]/Profile::Gpu::Install::Vgpu/Package[arbutus-cloud-vgpu-repo]/ensure) change from 'absent' to 'present' failed: Execution of '/usr/bin/rpm -i http://repo.arbutus.cloud.computecanada.ca/pulp/repos/centos/arbutus-cloud-vgpu-repo.el7.noarch.rpm' returned 1: curl: (7) Failed connect to repo.arbutus.cloud.computecanada.ca:80; Connection timed out
```
Is that package somehow private?

**Comment by ocaisa** [comment]
Even if I install the drivers by hand according to the instructions at https://apps.fz-juelich.de/jsc/hps/jusuf/cloud/virtual_gpus.html#install-nvidia-driver-for-vgpu-support , the node still does not appear in Slurm due to another failure later:
```
Feb  4 16:13:37 gpu-node1 puppet-agent[18248]: Execution of '/usr/bin/yum -d 0 -e 0 -y install slurm' returned 1: Error: Package: slurm-19.05.8-1.el7.x86_64 (slurm-copr-repo
)
Feb  4 16:13:37 gpu-node1 puppet-agent[18248]:           Requires: libnvidia-ml.so.1()(64bit)
```
which exists, but I think not in the directory puppet expects (`/usr/lib/libnvidia-ml.so.1` instead of `/usr/lib/nvidia/libnvidia-ml.so.1`)

**Comment by cmd-ntrf** [comment]
The yum repo is private on Arbutus. I did not plan originally for MC to run on other OpenStack cluster with VGPUs, that was shortsighted on my part. We will need to be able to define the source of the drivers.

Regarding the installation of the driver by hand:
Slurm's RPM expects the requirement `libnvidia-ml.so.1()(64bit)` to be filled by another RPM. To solve this issue, we would need a RPM that fakes providing the file.

**Comment by cmd-ntrf** [comment]
Slurm removed the dependency to `libnvidia-ml.so` when installing from RPMs since Slurm 20 to allow manual install:
https://github.com/SchedMD/slurm/commit/1be5492c274e170451ed18763e7eeea826f57cb7

This means when configuring Magic Castle with Slurm 20, yum should be able install the slurm rpm. I should able to cherry-pick the commit for our rpm build of Slurm 19.

What will be left to do is generalize the installation of the drivers for VGPUs to allow installing from RPMs or from binary installer and make sure the Arbutus code does not run outside of Arbutus.

**Comment by cmd-ntrf** [comment]
I have updated the Slurm19 RPMs build to remove the dependency on `libnvidia-ml.so`.
The logic for building the rpm is available here : https://github.com/cmd-ntrf/copr_scripts

**Comment by ocaisa** [comment]
With that change things are looking good:
```
[centos@login1 ~]$ scontrol show node=gpu-node1
NodeName=gpu-node1 Arch=x86_64 CoresPerSocket=1 
   CPUAlloc=0 CPUTot=2 CPULoad=0.18
   AvailableFeatures=(null)
   ActiveFeatures=(null)
   Gres=gpu:1(S:0-1)
   NodeAddr=gpu-node1 NodeHostName=gpu-node1 Version=19.05.8
   OS=Linux 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 
   RealMemory=7982 AllocMem=0 FreeMem=5489 Sockets=2 Boards=1
   State=IDLE ThreadsPerCore=1 TmpDisk=0 Weight=2 Owner=N/A MCS_label=N/A
   Partitions=cpubase_bycore_b1 
   BootTime=2021-02-08T08:39:19 SlurmdStartTime=2021-02-08T08:43:14
   CfgTRES=cpu=2,mem=7982M,billing=2,gres/gpu=1
   AllocTRES=
   CapWatts=n/a
   CurrentWatts=0 AveWatts=0
   ExtSensorsJoules=n/s ExtSensorsWatts=0 ExtSensorsTemp=n/s
```

Here's what manual driver installation looks like for me:
```
sudo yum install -y gcc make kernel-devel elfutils-libelf-devel libglvnd libglvnd-devel pciutils gcc-c++ epel-release
curl -o /tmp/NVIDIA-Driver.latest.run https://hpsrepo.fz-juelich.de/jusuf/nvidia/NVIDIA-Driver.latest
chmod 755 /tmp/NVIDIA-Driver.latest.run
sudo mkdir /etc/nvidia
curl -o /tmp/gridd.conf https://hpsrepo.fz-juelich.de/jusuf/nvidia/gridd.conf
sudo mv /tmp/gridd.conf /etc/nvidia/gridd.conf
sudo /tmp/NVIDIA-Driver.latest.run --ui=none --no-questions --disable-nouveau
sudo shutdown 1 -r
```
so the two unique things are the driver location and the license server information in `gridd.conf`. For the driver, I assume that this is the same for everyone, only the location will differ. In our `gridd.conf`, there are 4 modified values from the template:  `ServerAddress`, `ServerPort`, `FeatureType`, `LicenseInterval`.

**Comment by cmd-ntrf** [comment]
I now have a branch in magic_castle and puppet-magic_castle that should be able to install VGPU drivers correctly on JUSUF cloud.
https://github.com/ComputeCanada/magic_castle/tree/keystone - magic_castle, branch : keystone
https://github.com/ComputeCanada/puppet-magic_castle/blob/dev/vgpu2/site/profile/manifests/gpu.pp#L160 puppet-magic_castle, branch: dev/vgpu2

The magic_castle branch also paves the way to enable auto-scaling of nodes with Slurm.

**Comment by cmd-ntrf** [comment]
Everything is now merged.

Fixed.
