### ISSUE TITLE
Update Slurm default version to 20?

### ISSUE THREAD

**Issue by verdurin** [ComputeCanada/puppet-magic_castle#98]
Now that #51 is fixed, can the Slurm default version safely be changed to `20`?

**Comment by cmd-ntrf** [comment]
Almost, your issue made me realized the parameter to change the Slurm was not documented and that there is two different Slurm 20, Slurm 20.02 and Slurm 20.11.

I have refactor the slurm_version variable to accept either `19.05` or `20.11` in PR #99.

Once it is merged, I will confirm Slurm 20.11 is working properly with VGPUs and if it is, we will change the default to 20.11.

**Comment by cmd-ntrf** [comment]
Done.
